services:
  vault:
    image: hashicorp/vault
    container_name: geri-erp-vault
    environment:
      VAULT_ADDR: "https://localhost:8200"
      VAULT_API_ADDR: "https://localhost:8200"
      VAULT_ADDRESS: "https://localhost:8200"
      # VAULT_UI: true
      # VAULT_TOKEN:
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    volumes:
      - /vault/logs:/vault/logs/:rw
      - /vault/file/:/vault/file/:rw
      - /vault/config/:/vault/config/
      - /vault/certs:/certs/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl
