services:
  vault:
    image: hashicorp/vault
    container_name: geri-erp-vault
    environment:
      VAULT_ADDR: "https://vault.geriassistbot.com:8200"
      VAULT_API_ADDR: "https://vault.geriassistbot.com:8200"
      VAULT_ADDRESS: "https://vault.geriassistbot.com:8200"
      # VAULT_UI: true
      # VAULT_TOKEN:
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    volumes:
      - ./logs:/vault/logs/:rw
      - ./data:/vault/data/:rw
      - ./config:/vault/config/:rw
      - ./certs:/certs/:rw
      - ./file:/vault/file/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl